title: Naibao Zhao
url: "https://nzhao925.github.io" 
baseurl: "https://nzhao925.github.io" 

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://nzhao925.github.io" 
footer_text: "&copy Naibao Zhao 2024. <code>Last updated: December, 2025<br/><br/></code>"

sass:
    style: compressed
    sass_dir: _sass

nav:
 # - name: "About"
 #  link: "/researcher/"
 - name: "Research"
   link: "research"
 - name: "Teaching"
   link: "teaching"
 - name: "Former Students"
   link: "former_students"
 - name: "CV"
   link: "cv"
 - name: "SSSI Chengdu"
   link: "SSSI2019"
